package prueba_figuras;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Circulo1 = new javax.swing.JTextField();
        jTextField_Circulo2 = new javax.swing.JTextField();
        jTextField_Circulo3 = new javax.swing.JTextField();
        jButton_Circulo1 = new javax.swing.JButton();
        jButton_Circulo2 = new javax.swing.JButton();
        jButton_Circulo3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Cuadrado1 = new javax.swing.JTextField();
        jTextField_Cuadrado2 = new javax.swing.JTextField();
        jTextField_Cuadrado3 = new javax.swing.JTextField();
        jButton_Cuadrado1 = new javax.swing.JButton();
        jButton_Cuadrado2 = new javax.swing.JButton();
        jButton_Cuadrado3 = new javax.swing.JButton();
        BtnRectangulo2 = new javax.swing.JButton();
        BtnRectangulo1 = new javax.swing.JButton();
        BtnRectangulo3 = new javax.swing.JButton();
        TxtRectangulo1 = new javax.swing.JTextField();
        TxtRectangulo3 = new javax.swing.JTextField();
        TxtRectangulo4 = new javax.swing.JTextField();
        TxtRectangulo2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtTriangulo1 = new javax.swing.JTextField();
        TxtTriangulo3 = new javax.swing.JTextField();
        TxtTriangulo2 = new javax.swing.JTextField();
        TxtTriangulo4 = new javax.swing.JTextField();
        TxtTriangulo5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        BtnTriangulo1 = new javax.swing.JButton();
        BtnTriangulo2 = new javax.swing.JButton();
        BtnTriangulo3 = new javax.swing.JButton();
        BtnTriangulo4 = new javax.swing.JButton();
        btntipo = new javax.swing.JButton();
        TxtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jLabel1.setText("Circulo");
        jLabel1.setToolTipText("");
        jLabel1.setAutoscrolls(true);
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 16));

        jLabel2.setText("Radio");

        jLabel3.setText("Area");

        jLabel4.setText("Perimetro");

        jTextField_Circulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Circulo1ActionPerformed(evt);
            }
        });

        jTextField_Circulo2.setAutoscrolls(false);
        jTextField_Circulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Circulo2ActionPerformed(evt);
            }
        });

        jButton_Circulo1.setText("Borrar");
        jButton_Circulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Circulo1ActionPerformed(evt);
            }
        });

        jButton_Circulo2.setText("Calcular Area");
        jButton_Circulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Circulo2ActionPerformed(evt);
            }
        });

        jButton_Circulo3.setText("Calcular Perimetro");
        jButton_Circulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Circulo3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cuadrado");

        jLabel6.setText("Lado");

        jLabel7.setText("Area");

        jLabel8.setText("Perimetro");

        jTextField_Cuadrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cuadrado1ActionPerformed(evt);
            }
        });

        jTextField_Cuadrado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cuadrado3ActionPerformed(evt);
            }
        });

        jButton_Cuadrado1.setText("Borrar");
        jButton_Cuadrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cuadrado1ActionPerformed(evt);
            }
        });

        jButton_Cuadrado2.setText("Calcular Area");
        jButton_Cuadrado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cuadrado2ActionPerformed(evt);
            }
        });

        jButton_Cuadrado3.setText("Calcular Perimetro");
        jButton_Cuadrado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cuadrado3ActionPerformed(evt);
            }
        });

        BtnRectangulo2.setText("Calcular Area");
        BtnRectangulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRectangulo2ActionPerformed(evt);
            }
        });

        BtnRectangulo1.setText("Borrar");
        BtnRectangulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRectangulo1ActionPerformed(evt);
            }
        });

        BtnRectangulo3.setText("Calcular Perimetro");
        BtnRectangulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRectangulo3ActionPerformed(evt);
            }
        });

        TxtRectangulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRectangulo1ActionPerformed(evt);
            }
        });

        TxtRectangulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRectangulo3ActionPerformed(evt);
            }
        });

        TxtRectangulo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRectangulo4ActionPerformed(evt);
            }
        });

        TxtRectangulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRectangulo2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Perimetro");

        jLabel10.setText("Area");

        jLabel11.setText("Base");

        jLabel12.setText("Rectangulo");

        jLabel13.setText("Altura");

        jLabel14.setText("Triangulo");

        TxtTriangulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTriangulo1ActionPerformed(evt);
            }
        });

        TxtTriangulo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTriangulo5ActionPerformed(evt);
            }
        });

        jLabel15.setText("Altura");

        jLabel16.setText("Base");

        jLabel17.setText("Area");

        jLabel18.setText("Perimetro");

        jLabel19.setText("Hipotenusa");

        BtnTriangulo1.setText("Borra");
        BtnTriangulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTriangulo1ActionPerformed(evt);
            }
        });

        BtnTriangulo2.setText("Calcular Area");
        BtnTriangulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTriangulo2ActionPerformed(evt);
            }
        });

        BtnTriangulo3.setText("Calcular Perimetro");
        BtnTriangulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTriangulo3ActionPerformed(evt);
            }
        });

        BtnTriangulo4.setText("Calcular Hipotenusa");
        BtnTriangulo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTriangulo4ActionPerformed(evt);
            }
        });

        btntipo.setText("Calcular tipo de triangulo");
        btntipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntipoActionPerformed(evt);
            }
        });

        TxtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_Circulo3)
                            .addComponent(jTextField_Circulo1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Circulo2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtRectangulo3)
                            .addComponent(TxtRectangulo4)
                            .addComponent(TxtRectangulo2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtRectangulo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_Circulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Circulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Circulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnRectangulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnRectangulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnRectangulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(199, 199, 199))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Cuadrado1)
                            .addComponent(TxtTriangulo4)
                            .addComponent(TxtTriangulo3)
                            .addComponent(TxtTriangulo2)
                            .addComponent(TxtTriangulo1)
                            .addComponent(TxtTriangulo5)
                            .addComponent(jTextField_Cuadrado2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jTextField_Cuadrado3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Cuadrado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Cuadrado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Cuadrado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTriangulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTriangulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTriangulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTriangulo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtTipo)
                            .addComponent(btntipo, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addContainerGap(69, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Circulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Circulo1)
                    .addComponent(jLabel6)
                    .addComponent(jButton_Cuadrado1)
                    .addComponent(jTextField_Cuadrado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Circulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Circulo2)
                    .addComponent(jLabel7)
                    .addComponent(jButton_Cuadrado2)
                    .addComponent(jTextField_Cuadrado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField_Circulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Cuadrado3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Circulo3)
                        .addComponent(jLabel8)
                        .addComponent(jTextField_Cuadrado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtTriangulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(BtnTriangulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTriangulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(BtnTriangulo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTriangulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(BtnTriangulo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTriangulo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(BtnTriangulo4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtRectangulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtRectangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(BtnRectangulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtRectangulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRectangulo2)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnRectangulo3)
                            .addComponent(TxtRectangulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Circulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Circulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Circulo1ActionPerformed

    private void jButton_Circulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Circulo2ActionPerformed
        // TODO add your handling code here:
        double area;
        int radio = Integer.parseInt(jTextField_Circulo1.getText());
        Circulo figura1 = new Circulo(radio);
        area = figura1.calcularArea();
        jTextField_Circulo2.setText(String.valueOf(area));
    }//GEN-LAST:event_jButton_Circulo2ActionPerformed

    private void jButton_Circulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Circulo3ActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int radio = Integer.parseInt(jTextField_Circulo1.getText());
        Circulo figura1 = new Circulo(radio);
        perimetro = figura1.calcularPerimetro();
        jTextField_Circulo3.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_jButton_Circulo3ActionPerformed

    private void jTextField_Circulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Circulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Circulo2ActionPerformed

    private void jButton_Circulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Circulo1ActionPerformed
        // TODO add your handling code here:
        jTextField_Circulo1.setText("");
        jTextField_Circulo2.setText("");
        jTextField_Circulo3.setText("");
    }//GEN-LAST:event_jButton_Circulo1ActionPerformed

    private void jButton_Cuadrado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cuadrado2ActionPerformed
        // TODO add your handling code here:
        double area;
        int lado = Integer.parseInt(jTextField_Cuadrado1.getText());
        Cuadrado figura2 = new Cuadrado(lado);
        area = figura2.calcularArea();
        jTextField_Cuadrado2.setText(String.valueOf(area));
        
    }//GEN-LAST:event_jButton_Cuadrado2ActionPerformed

    private void jTextField_Cuadrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cuadrado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cuadrado1ActionPerformed

    private void jButton_Cuadrado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cuadrado3ActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int lado = Integer.parseInt(jTextField_Cuadrado1.getText());
        Cuadrado figura2 = new Cuadrado(lado);
        perimetro = figura2.calcularPerimetro();
        jTextField_Cuadrado3.setText(String.valueOf(perimetro));
        
    }//GEN-LAST:event_jButton_Cuadrado3ActionPerformed

    private void jButton_Cuadrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cuadrado1ActionPerformed
        // TODO add your handling code here:
        jTextField_Cuadrado1.setText("");
        jTextField_Cuadrado2.setText("");
        jTextField_Cuadrado3.setText("");
    }//GEN-LAST:event_jButton_Cuadrado1ActionPerformed

    private void jTextField_Cuadrado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cuadrado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cuadrado3ActionPerformed

    private void BtnRectangulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRectangulo2ActionPerformed
        // TODO add your handling code here:
        double area;
        int altura = Integer.parseInt(TxtRectangulo1.getText());
        int base = Integer.parseInt(TxtRectangulo2.getText());
        Rectangulo figura3 = new Rectangulo(altura,base);
        area = figura3.calcularArea();
        TxtRectangulo3.setText(String.valueOf(area));
    }//GEN-LAST:event_BtnRectangulo2ActionPerformed

    private void BtnRectangulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRectangulo1ActionPerformed
        // TODO add your handling
        TxtRectangulo1.setText("");
        TxtRectangulo2.setText("");
        TxtRectangulo3.setText("");
        TxtRectangulo4.setText("");
        
    }//GEN-LAST:event_BtnRectangulo1ActionPerformed

    private void BtnRectangulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRectangulo3ActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int altura = Integer.parseInt(TxtRectangulo1.getText());
        int base = Integer.parseInt(TxtRectangulo2.getText());
        Rectangulo figura3 = new Rectangulo(altura,base);
        perimetro = figura3.calcularPerimetro();
        TxtRectangulo4.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_BtnRectangulo3ActionPerformed

    private void TxtRectangulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRectangulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRectangulo1ActionPerformed

    private void TxtRectangulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRectangulo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRectangulo3ActionPerformed

    private void TxtRectangulo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRectangulo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRectangulo4ActionPerformed

    private void TxtRectangulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRectangulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRectangulo2ActionPerformed

    private void TxtTriangulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTriangulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTriangulo1ActionPerformed

    private void TxtTriangulo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTriangulo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTriangulo5ActionPerformed

    private void BtnTriangulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTriangulo2ActionPerformed
        // TODO add your handling code here:
        double area;
        int altura = Integer.parseInt(TxtTriangulo1.getText());
        int base = Integer.parseInt(TxtTriangulo2.getText());
        Triangulo figura4 = new Triangulo(altura,base);
        area = figura4.calcularArea();
        TxtTriangulo3.setText(String.valueOf(area));
    }//GEN-LAST:event_BtnTriangulo2ActionPerformed

    private void btntipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntipoActionPerformed
        // TODO add your handling code here:
        int altura = Integer.parseInt(TxtTriangulo1.getText());
        int base = Integer.parseInt(TxtTriangulo2.getText());
        Triangulo figura4 = new Triangulo(altura,base);
        TxtTipo.setText(figura4.determinarTipoTriángulo());
        
    }//GEN-LAST:event_btntipoActionPerformed

    private void TxtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTipoActionPerformed

    private void BtnTriangulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTriangulo3ActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int altura = Integer.parseInt(TxtTriangulo1.getText());
        int base = Integer.parseInt(TxtTriangulo2.getText());
        Triangulo figura4 = new Triangulo(altura,base);
        perimetro = figura4.calcularPerímetro();
        TxtTriangulo4.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_BtnTriangulo3ActionPerformed

    private void BtnTriangulo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTriangulo4ActionPerformed
        // TODO add your handling code here:
        double hipotenusa;
        int altura = Integer.parseInt(TxtTriangulo1.getText());
        int base = Integer.parseInt(TxtTriangulo2.getText());
        Triangulo figura4 = new Triangulo(altura,base);
        hipotenusa = figura4.calcularHipotenusa();
        TxtTriangulo5.setText(String.valueOf(hipotenusa));
    }//GEN-LAST:event_BtnTriangulo4ActionPerformed

    private void BtnTriangulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTriangulo1ActionPerformed
        // TODO add your handling code here:
        TxtTriangulo1.setText("");
        TxtTriangulo2.setText("");
        TxtTriangulo3.setText("");
        TxtTriangulo4.setText("");
        TxtTriangulo5.setText("");
        TxtTipo.setText("");
        
    }//GEN-LAST:event_BtnTriangulo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRectangulo1;
    private javax.swing.JButton BtnRectangulo2;
    private javax.swing.JButton BtnRectangulo3;
    private javax.swing.JButton BtnTriangulo1;
    private javax.swing.JButton BtnTriangulo2;
    private javax.swing.JButton BtnTriangulo3;
    private javax.swing.JButton BtnTriangulo4;
    private javax.swing.JTextField TxtRectangulo1;
    private javax.swing.JTextField TxtRectangulo2;
    private javax.swing.JTextField TxtRectangulo3;
    private javax.swing.JTextField TxtRectangulo4;
    private javax.swing.JTextField TxtTipo;
    private javax.swing.JTextField TxtTriangulo1;
    private javax.swing.JTextField TxtTriangulo2;
    private javax.swing.JTextField TxtTriangulo3;
    private javax.swing.JTextField TxtTriangulo4;
    private javax.swing.JTextField TxtTriangulo5;
    private javax.swing.JButton btntipo;
    private javax.swing.JButton jButton_Circulo1;
    private javax.swing.JButton jButton_Circulo2;
    private javax.swing.JButton jButton_Circulo3;
    private javax.swing.JButton jButton_Cuadrado1;
    private javax.swing.JButton jButton_Cuadrado2;
    private javax.swing.JButton jButton_Cuadrado3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_Circulo1;
    private javax.swing.JTextField jTextField_Circulo2;
    private javax.swing.JTextField jTextField_Circulo3;
    private javax.swing.JTextField jTextField_Cuadrado1;
    private javax.swing.JTextField jTextField_Cuadrado2;
    private javax.swing.JTextField jTextField_Cuadrado3;
    // End of variables declaration//GEN-END:variables
}
